server:
  port: 7001

spring:
  application:
    name: json-stock-quote-ticker
  jackson:
    serialization:
      write_dates_as_timestamps: false

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.stockgeeks.ticker.service.JsonSerializerInstant
      client-id: "json-raw-quote-producer-spring-kafka"
      properties:
        enable:
          idempotence: true

generator:
  tick:
    enabled: true
    start-delay-milliseconds: 5000
    interval-milliseconds: 2
    num-threads: 1

# Enable all spring boot actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: "ALWAYS"

  metrics:
    tags:
      application: ${spring.application.name}
